"""add_username_field_to_user

Revision ID: 2329adb4c124
Revises: e02645ffeea7
Create Date: 2025-08-17 17:49:44.962153

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2329adb4c124"
down_revision: Union[str, None] = "e02645ffeea7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 먼저 nullable=True로 컬럼 추가
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=True))

    # 기존 사용자들에게 임시 username 생성 (email 기반)
    op.execute(
        """
        UPDATE users 
        SET username = CONCAT('user_', id) 
        WHERE username IS NULL
    """
    )

    # NOT NULL 제약조건 추가
    op.alter_column("users", "username", nullable=False)

    # 인덱스 생성
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
