"""Add media model

Revision ID: e02645ffeea7
Revises: 0fdeb196571d
Create Date: 2025-08-16 17:30:47.113596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e02645ffeea7'
down_revision: Union[str, None] = '0fdeb196571d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_accounts', 'id_token')
    op.drop_column('auth_accounts', 'session_state')
    op.add_column('github_repositories', sa.Column('watchers', sa.Integer(), nullable=False))
    op.add_column('github_repositories', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.add_column('github_repositories', sa.Column('is_fork', sa.Boolean(), nullable=False))
    op.add_column('github_repositories', sa.Column('last_commit_sha', sa.String(length=40), nullable=True))
    op.add_column('github_repositories', sa.Column('last_commit_message', sa.Text(), nullable=True))
    op.add_column('github_repositories', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('github_repositories', sa.Column('sync_error_message', sa.Text(), nullable=True))
    op.alter_column('github_repositories', 'github_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('github_repositories', 'language',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.add_column('sessions', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_sessions_session_token', table_name='sessions')
    op.create_unique_constraint(None, 'sessions', ['session_token'])
    op.drop_column('sessions', 'is_active')
    op.drop_column('sessions', 'last_accessed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_accessed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='unique')
    op.create_index('ix_sessions_session_token', 'sessions', ['session_token'], unique=True)
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('sessions', 'last_accessed_at')
    op.alter_column('github_repositories', 'language',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('github_repositories', 'github_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('github_repositories', 'sync_error_message')
    op.drop_column('github_repositories', 'last_synced_at')
    op.drop_column('github_repositories', 'last_commit_message')
    op.drop_column('github_repositories', 'last_commit_sha')
    op.drop_column('github_repositories', 'is_fork')
    op.drop_column('github_repositories', 'is_private')
    op.drop_column('github_repositories', 'watchers')
    op.add_column('auth_accounts', sa.Column('session_state', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('auth_accounts', sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
